# Generated by Django 5.2.1 on 2025-06-22 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0025_alter_cargo_especialidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alumnos.turno')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asistencia.tipoasistencia')),
            ],
            options={
                'unique_together': {('alumno', 'fecha', 'turno', 'tipo')},
            },
        ),
    ]
