# Generated by Django 5.2.1 on 2025-06-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='presente',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('T', 'Tarde'), ('AP', 'Ausente con presencia')], default='P', max_length=2),
        ),
    ]
