# Generated by Django 5.2.1 on 2025-06-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0027_alter_curso_nombre'),
        ('asistencia', '0002_remove_asistencia_presente_asistencia_estado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('alumno', 'fecha', 'tipo')},
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='turno',
        ),
    ]
