# Generated by Django 5.2 on 2025-05-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=100, verbose_name='Distrito')),
                ('nombre_escuela', models.CharField(max_length=100, verbose_name='Nombre de la escuela')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('sector_gestion', models.CharField(choices=[('estatal', 'Estatal'), ('privado', 'Privado')], default='estatal', max_length=20, verbose_name='Sector de gestión')),
                ('clave_provincial', models.CharField(max_length=50, verbose_name='Clave provincial')),
                ('cue', models.CharField(max_length=50, verbose_name='CUE')),
            ],
            options={
                'verbose_name': 'Configuración Escolar',
                'verbose_name_plural': 'Configuración Escolar',
            },
        ),
    ]
