# Generated by Django 5.2 on 2025-05-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracionescolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionescolar',
            name='sector_gestion',
            field=models.CharField(choices=[('Estatal', 'Estatal'), ('Privado', 'Privado')], default='statal', max_length=20, verbose_name='Sector de gestión'),
        ),
    ]
