# Generated by Django 5.2 on 2025-05-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_options_alter_aula_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='situacion_revista',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='telefono_alternativo',
        ),
        migrations.AddField(
            model_name='materia',
            name='situacion_revista',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
