# Generated by Django 5.2 on 2025-05-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_remove_docente_situacion_revista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
