# Generated by Django 5.2 on 2025-05-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_docente_telefono_emergencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='tipo',
            field=models.CharField(choices=[('TALLER', 'Taller'), ('TEORIA', 'Teoria')], default='TE', max_length=20),
        ),
    ]
