# Generated by Django 5.2 on 2025-05-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alter_materia_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterField(
            model_name='materia',
            name='tipo',
            field=models.CharField(choices=[('TALLER', 'Taller'), ('TEORIA', 'Teoria')], default='TEORIA', max_length=20),
        ),
    ]
