# Generated by Django 5.2 on 2025-05-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_alter_alumno_options_alter_materia_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='año',
        ),
        migrations.AlterField(
            model_name='aula',
            name='tipo',
            field=models.CharField(choices=[('AULA', 'Aula'), ('LAB.', 'Laboratorio'), ('S.U.M', 'S.U.M'), ('BIBLIO.', 'Biblioteca')], default='AULA', max_length=10),
        ),
    ]
