# Generated by Django 5.2 on 2025-05-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_remove_curso_activo_remove_curso_año_alter_aula_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='situacion_revista',
            field=models.CharField(choices=[('SUPLENTE', 'SUPLENTE'), ('PROVICIONAL', 'PROVICIONAL'), ('TITULAR_INT', 'TITULAR INT.'), ('TITULAR', 'TITULAR')], default='SUPLENTE', max_length=100),
        ),
    ]
