# Generated by Django 5.2 on 2025-05-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_alter_materia_situacion_revista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='situacion_revista',
            field=models.CharField(choices=[('SUPLENTE', 'SUPLENTE'), ('PROVICIONAL', 'PROVICIONAL'), ('TITULAR INT.', 'TITULAR_INT'), ('TITULAR', 'TITULAR')], default='SUPLENTE', max_length=100),
        ),
    ]
