# Generated by Django 5.2 on 2025-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0010_alter_materia_situacion_revista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='situacion_revista',
        ),
        migrations.AddField(
            model_name='grupomateria',
            name='situacion_revista',
            field=models.CharField(choices=[('SUPLENTE', 'SUPLENTE'), ('PROVISIONAL', 'PROVISIONAL'), ('TITULAR INT.', 'TITULAR_INT'), ('TITULAR', 'TITULAR')], default='SUPLENTE', max_length=100),
        ),
    ]
