# Generated by Django 5.2 on 2025-05-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0011_remove_materia_situacion_revista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='forma_ingreso',
            field=models.CharField(choices=[('TALLER', 'Taller'), ('TEORIA', 'Teoria')], default='ACTO PUBLICO DIGITAL', max_length=30),
        ),
    ]
