# Generated by Django 5.2 on 2025-05-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0012_alter_materia_forma_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='forma_ingreso',
            field=models.CharField(choices=[('MAD', 'M.A.D'), ('REUBICADO', 'REUBICADO'), ('APD', 'ACTO PUBLICO DIGITAL'), ('OTROS', 'OTROS')], default='ACTO PUBLICO DIGITAL', max_length=30),
        ),
    ]
