# Generated by Django 5.2 on 2025-05-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0013_alter_materia_forma_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='forma_ingreso',
            field=models.CharField(choices=[('M.A.D', 'MAD'), ('REUBICADO', 'REUBICADO'), ('ACTO PUBLICO DIGITAL', 'APD'), ('OTROS', 'OTROS')], default='ACTO PUBLICO DIGITAL', max_length=30),
        ),
    ]
