# Generated by Django 5.2 on 2025-06-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0014_alter_materia_forma_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
