# Generated by Django 5.2 on 2025-06-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0015_alter_especialidad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
