# Generated by Django 5.2 on 2025-06-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0016_alter_turno_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='forma_ingreso',
            field=models.CharField(choices=[('M.A.D', 'MAD'), ('REUBICADO', 'REUBICADO'), ('ACTO PUBLICO DIGITAL', 'APD'), ('ACTO PUBLICO', 'AP'), ('DESTINO DEFINITIVO', 'DD'), ('PROPUESTA NOMBRAMIENTO', 'PN'), ('PROYECTO Y ELECCION', 'PE'), ('DISPOSICION', 'DIS'), ('OTROS', 'OTROS')], default='ACTO PUBLICO DIGITAL', max_length=30),
        ),
    ]
