# Generated by Django 5.2.1 on 2025-06-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0017_alter_materia_forma_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='forma_ingreso',
            field=models.CharField(choices=[('M.A.D', 'MAD'), ('REUBICADO', 'REUBICADO'), ('APD', 'ACTO PUBLICO DIGITAL'), ('AP', 'ACTO PUBLICO'), ('DD', 'DESTINO DEFINITIVO'), ('PN', 'PROPUESTA NOMBRAMIENTO'), ('PE', 'PROYECTO Y ELECCION'), ('DIS', 'DISPOSICION'), ('OTROS', 'OTROS')], default='ACTO PUBLICO DIGITAL', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='grupomateria',
            unique_together={('materia', 'grupo', 'docente')},
        ),
    ]
