# Generated by Django 5.2.1 on 2025-06-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0018_alter_materia_forma_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='numero_dispo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
