# Generated by Django 5.2 on 2025-06-09 18:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0019_materia_numero_dispo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curso', to='alumnos.curso'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='especialidades',
            field=models.ManyToManyField(related_name='especialidad', to='alumnos.especialidad'),
        ),
        migrations.CreateModel(
            name='TipoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('curso', models.ManyToManyField(blank=True, related_name='curso_cargo', to='alumnos.curso')),
                ('especialidades', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especialidad_cargo', to='alumnos.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cuil', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{8}-\\d{1}$')])),
                ('domicilio', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('numero_legajo', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.tipocargo')),
            ],
        ),
    ]
