# Generated by Django 5.2 on 2025-06-09 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0020_alter_materia_curso_alter_materia_especialidades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocargo',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='tipocargo',
            name='especialidades',
        ),
        migrations.AddField(
            model_name='cargo',
            name='curso',
            field=models.ManyToManyField(blank=True, related_name='curso_cargo', to='alumnos.curso'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='especialidades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especialidad_cargo', to='alumnos.especialidad'),
        ),
    ]
