# Generated by Django 5.2 on 2025-06-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0022_alter_cargo_especialidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
