# Generated by Django 5.2 on 2025-06-12 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0023_alter_cargo_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='especialidades',
            field=models.ForeignKey(blank=True, default='Sin Especialidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especialidad_cargo', to='alumnos.especialidad'),
        ),
    ]
