# Generated by Django 5.2.1 on 2025-06-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0025_alter_cargo_especialidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='especialidades',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='turnos',
        ),
    ]
