# Generated by Django 5.2.1 on 2025-06-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0026_remove_curso_especialidades_remove_curso_turnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
