# Generated by Django 5.2.1 on 2025-07-09 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0027_alter_curso_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='cuil',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='numero_legajo',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='telefono_emergencia',
        ),
        migrations.AddField(
            model_name='cargo',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='alumnos.docente'),
        ),
    ]
